name: CI Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: make all

        #    - name: Test
        #      run: make test-unit
